##
## EPITECH PROJECT, 2021
## Makefile
## File description:
## Compiles the binaries
##

all:
	@make -C generator/
	@make -C solver/

clean:
	@make clean -C generator/
	@make clean -C solver/

re: clean all