- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Ensure Nginx is running and enabled to start on boot
  service:
    name: nginx
    state: started
    enabled: yes
