global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "codelab-monitor"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: docker
    static_configs:
      - targets: ["host.docker.internal:9323"]

  - job_name: node
    static_configs:
    - targets: ['app-web961944.westeurope.cloudapp.azure.com:9100']

  - job_name: 'alertmanager'
    static_configs:
    - targets: ['app-web961944.westeurope.cloudapp.azure.com:9093']

  - job_name: mysql
    static_configs:
    - targets: ['app-database241233.westeurope.cloudapp.azure.com:9104']
    # In the app-database machine, put .mysqld_exporter.cnf in /etc folder and mysql_exporter.service in /etc/systemd/system folder

  - job_name: db_node
    static_configs:
    - targets: ['app-database241233.westeurope.cloudapp.azure.com:9100']