services:
  db:
    image: postgres:15
    container_name: backend_db
    restart: always
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: backend_db
    volumes:
      - db-data:/var/lib/postgresql

volumes:
  db-data:
