services:
  backend:
    build:
      context: .
    container_name: backend
    restart: always
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: backend_db
      PGPORT: 5432
      PGHOST: db
    ports:
      - 4000:4000
    networks:
      - app
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: backend_db
    restart: always
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: backend_db
    networks:
      - app
    volumes:
      - db-data:/var/lib/postgresql

volumes:
  db-data:

networks:
  app:
