- name: Copy redis.conf script to serv
  copy:
    src: /roles/redis/files/redis.conf
    dest: /etc/redis/redis.conf

- name: Allow remote access on the redis server
  lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^bind'
    line: 'bind 0.0.0.0'
    state: present
  notify:
    - Restart Redis

- name: Restart Redis
  systemd:
    name: redis
    state: restarted
    enabled: yes

- name: Start Redis
  systemd:
    name: redis
    state: started

- name: Stop Redis
  systemd:
    name: redis
    state: stopped

- name: Enable Redis
  systemd:
    name: redis
    enabled: yes